# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: 80x24
title: Eight by Twenty-Four (80x24)
email: tfanelli@zblservices.com
description: > # this means to ignore newlines until "baseurl:"
  Eighty by Twenty Four (80x24) is a z/OS Mainframe blog by ZBL Services, Inc's Tim Fanelli. Tim has been a mainframer since 2000, and focuses on skills training, education, training, and productivity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eightybytwentyfour.com" # the base hostname & protocol for your site
twitter_username: zblservices
github_username:  doctorbatch

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
